targetWords = [
    'about',
    'acted',
    'added',
    'after',
    'aging',
    'alarm', 'alert', 'alien', 'align', 'alone', 'altar', 'alter',
    'angel', 'angle',
    'apple', 'apply',
    'array',
    'asked',
    'audio',

    'baked', 'bathe',
    'beach', 'beans', 'bears', 'beers', 'belly', 'bench', 'berry',
    'bills', 'birds', 'birth',
    'blind', 'block', 'blown',
    'board', 'books', 'bored', 'bound',
    'brain', 'brick', 'break', 'broke',
    'build',

    'candy', 'carts', 'cared', 'carry', 'carve', 'catch', 
    'chair', 'chick', 'chill', 'chips', 
    'clamp', 'clean',
    'cheek' ,'chewy', 'child', 'chili', 'chill',
    'click', 'clock', 'cloud', 'clubs',
    'coins', 'color', 'couch', 'covid',
    'craft', 'crane', 'crazy', 'cream', 'creep', 'crept', 'cries', 'crude',
    'cubes', 'curse',
    'cycle',

    'dance',
    'dirty',
    'doors', 'doubt',
    'drank', 'drink', 'drums', 'drunk', 
    'ducks', 'dusty',

    'eager', 'earth', 'eaten', 'eater',
    'eight',
    'elect',
    'enter',

    'faces', 'faith',
    'fifty', 'fight', 'files', 'finds',
    'fears', 'felts', 'fetch',
    'first',
    'flair', 'flick', 'flint', 'fling', 'floor', 'flute',
    'focus', 'folks', 'forty', 'found', 'foxes',
    'frame', 'freak', 'fresh', 'fruit',
    'fully', 'funny',

    'games', 'gates', 'gator',
    'gears', 'geese',
    'ghost',
    'goose', 'goods', 'gowns',
    'grace', 'graph', 'grass', 'grate', 'great', 'green', 'grill', 'groin', 'groom', 'gross', 'grown',
    'guard', 'guess', 'guest', 'guide', 'guild', 'guilt',

    'hatch', 'hands', 'handy', 'happy', 'hatch', 'hater', 'hazel',
    'heard', 'heart', 'heels', 'hefty', 'hello', 'heist',
    'hints',
    'hosts', 'house', 'human',

    'idaho',
    'index', 'india',

    'joker', 'jokes', 'joint', 
    'jumps', 'jumpy',

    'kitty',

    'latch', 'lamps', 'lasts', 'later', 'laugh',
    'learn', 'least', 'leave', 'lemon', 'level',
    'liked', 'likes', 'lilly', 'light', 'limes',
    'local', 'loops', 'loose', 'loved', 'lover', 'lower',


    'magic', 'maker', 'masks', 'match',
    'medal', 'media', 'melon', 'melts',
    'miami', 'mined', 'miner',
    'money', 'month', 'moody', 'moons', 'motel', 'mound', 'mouse', 'mouth', 'moved',
    'muted',

    'names', 'nanny',
    'nerdy', 'never',
    'night',
    'noise', 'nosey', 'north',

    'ocean',
    'olives',
    'often',
    'onion',

    'patch', 'paint', 'pairs', 'pants', 'paper', 'paste',
    'peach', 'petty',
    'phone',
    'piano', 'pills', 'pilot', 'pinky', 'pipes', 'pizza',
    'plank', 'plain', 'plane', 'plate', 'plugs', 'pluto',
    'prank', 'press', 'price',
    'poker', 'point', 'polar', 'ports', 'pouch', 'pours',
    'punch',

    'radio', 'ratio', 'ranch', 'ratio', 'razer',
    'ready', 'reign', 'relax',
    'rider', 'rides', 'ripen', 'risen', 'right', 'river',
    'rolls',

    'sadly', 'saint', 'saved',
    'scabs', 'scent',
    'seats',
    'skies', 'skirt', 'skull', 'skunk',
    'seven',
    'shade', 'shake', 'shank', 'shark', 'sharp', 'shift', 'shine', 'shirt', 'shrug',
    'sissy', 'sized',
    'shoes', 'shoot', 'shore', 'short', 'shout',
    'slave', 'slide', 'slime',
    'small', 'smell', 'smelt', 'smile', 'smoke',
    'snack', 'snale',
    'socks', 'solar', 'south',
    'space', 'spade', 'spain', 'spank', 'spark', 'speak', 'spear', 'split', 'spook', 'spots', 'spray',
    'stack', 'stall', 'stand', 'stats', 'stars', 'stear', 'start', 'stale', 'state', 'steak', 'sting', 'stoop', 'stops', 'store', 'storm', 'stuff', 'style',
    'sugar',
    'sunny',
    'squid',

    'table',
    'teach', 'theft',
    'their', 'theme', 'these', 'think', 'thing', 'those', 'three',
    'tiles', 'timer',
    'trash', 'treat', 'trees', 'trick', 'truck', 'trunk', 'trust', 'truth',
    'today', 'tooth', 'tower',
    'turns',
    'tweak',

    'upper',
    'under', 'unfix', 'union', 'unite',

    'vibes', 'video',
    'voted', 'votes',

    'walls', 'water',
    'which', 'whips', 'whole',
    'wipes', 'witch',
    'words', 'works', 'worry', 'would',
    'wrong',

    'yacht',
    'young', 'yours',

    'zebra',

]